#!/bin/bash 

net_info=$(raven-cli getnetworkinfo)
node_ver=$(echo ${net_info} | jq -r '.subversion' | awk -F/ '{print $2}')
node_ip=$(echo ${net_info} | jq -r '.localaddresses[] | .address')
node_port=$(echo ${net_info} | jq -r '.localaddresses[] | .port')
node_score=$(echo ${net_info} | jq -r '.localaddresses[] | .score')
node_peer_count=$(echo ${net_info} | jq -r '.connections')

echo "Node version: ${node_ver}"
echo "Node IP/port: ${node_ip}/${node_port}"
echo "Node Peer Count: ${node_peer_count}"
echo "Node score: ${node_score}"

count=$(raven-cli getblockcount)
echo "block count: $count"

hash=$(raven-cli getblockhash $count)
echo "block hash: $hash"

t=$(raven-cli getblock "$hash" | grep '"time"' | awk '{print $2}' | sed -e 's/,$//g')
echo "block timestamp is: $t"

cur_t=$(date +%s); 
diff_t=$[$cur_t - $t]; 
echo -n "Difference is: "
echo $diff_t | awk '{printf "%d days, %d:%d:%d\n",$1/(60*60*24),$1/(60*60)%24,$1%(60*60)/60,$1%60}'